name: Comment on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create or Update Pull Request Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Your comment message here. You can use GitHub context variables like ${{ github.sha }} and ${{ github.event.number }}.
          number: ${{ github.event.number }} # This refers to the pull request number
