name: Create Check Run on Push

on: [push_request]

jobs:
  create-comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Release ${{ github.sha }} to <https://pr-${{ github.event.number }}.example.com>
