name: Create Check Run on Push

on: [push_request]

jobs:
  create-comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        - uses: jwalton/gh-find-current-pr@v1
          id: finder
        - uses: marocchino/sticky-pull-request-comment@v2
          with:
            number: ${{ steps.finder.outputs.pr }}
            message: |
              Test ${{ github.sha }} ended successfully.
              This message is from a push.
