name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Coverage Comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const coverage = 90;
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            const message = `Coverage: 90%`;

            github.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: prNumber,
              body: message
            });
