name: Build and Test application
run-name: Build and Test 🚀
on: [push, pull_request]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
      - uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
        uses: actions/setup-node@v3
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo " 🧪 Starting tests --> npm ci, build, and test"
      - run: |
          npm ci
          npm run build --if-present
          npm test
      - run: echo "🍏 This job's status is ${{ job.status }}."
