name: Build and Test client
run-name: Test Suite 🚀
on: [push]
jobs:
  Run Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
      - run: echo " 🧪 Starting tests"
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: npm ci, build and test
        run: |
          npm ci
          npm run build --if-present
          npm test 
      - run: echo "🍏 This job's status is ${{ job.status }}."
